[project]
name = "ditl_polars_example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "Tim Bossenmaier", email="bossenti@posteo.de"},
    {name = "Jochen Gietzen", email="jochen.gietzen@gmail.com"}
]
dependencies = [
    "ditl",
    "ditl-engine-pandas",
    "ditl-engine-polars",
    "ditl-rs-dbx-asset-bundle-jobs",
    "pandas>=3.0.1",
    "polars>=1.34.0",
    "pytest>=9.0.2",
    "tabulate>=0.10.0",
]

[tool.uv]
package = true

[tool.uv.sources]
ditl = { workspace = true }
ditl-engine-pandas = { workspace = true }
ditl-engine-polars = { workspace = true }
ditl-rs-dbx-asset-bundle-jobs = { workspace = true }

[tool.uv.build-backend]
module-name = ["ditl_polars_example"]
module-root = "src"
