repos:
  - repo: local
    hooks:
      - id: print_statement
        name: Check that print is not in the source code
        types: [ python ]
        entry: 'print\(.*\)'
        language: pygrep

      - id: ruff_fmt
        name: ruff_fmt
        language: python
        types: [ python ]
        entry: ruff format src/ tests/
        verbose: true

      - id: ruff_check
        name: ruff_check
        language: python
        types: [ python ]
        entry: ruff check src/ tests/
        verbose: true

      # - id: mypy
      #   name: mypy
      #   language: python
      #   types: [ python ]
      #   entry: mypy src/
      #   verbose: true

      - id: pylint
        name: pylint
        language: python
        types: [ python ]
        entry: pylint src/ tests/
        verbose: true

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v1.15.0'
  #   hooks:
  #     - id: mypy
  #       args: [--install-types]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
