[project]
name = "ditl"
version = "0.1.0"
description = "A library that aims to simplify etl/elt generation for standard use cases"
authors = [
    {name = "Jochen Gietzen", email="jochen.gietzen@gmail.com"},
    {name = "Tim Bossenmaier", email="bossenti@posteo.de"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "networkx>=3.4.2",
    "pandas>=2.3.1",
    "polars>=1.34.0",
    "pydantic>=2.11.5",
    "pyyaml>=6.0.2",
]

[tool.uv]
package = true

[tool.uv.build-backend]
module-name = ["ditl", "examples"]
module-root = "src"

[tool.mypy]
exclude = [
    "^one\\.py$",
    'two\.pyi$',
    '^three\.',
]

[tool.pylint.main]
fail-under = 10
ignore-patterns = ["^\\.#"]
jobs = 1
persistent = true
py-version = "3.11"
suggestion-mode = true

[tool.pylint.basic]
argument-naming-style = "snake_case"
attr-naming-style = "snake_case"
bad-names = ["foo", "bar", "baz", "toto", "tutu", "tata", "a", "b", "c"]
class-attribute-naming-style = "any"
class-const-naming-style = "UPPER_CASE"
class-naming-style = "PascalCase"
const-naming-style = "UPPER_CASE"
docstring-min-length = -1
function-naming-style = "snake_case"
good-names = ["i", "j", "k", "ex", "Run", "_", "df"]
inlinevar-naming-style = "any"
method-naming-style = "snake_case"
module-naming-style = "snake_case"
no-docstring-rgx = "^_"
property-classes = ["abc.abstractproperty"]
variable-naming-style = "snake_case"

[tool.pylint."messages control"]
disable = [
    "unused-argument",
    "missing-class-docstring",
    "missing-module-docstring",
]

[dependency-groups]
dev = [
    "commitizen>=4.8.2",
    "jupyter>=1.1.1",
    "mypy>=1.15.0",
    "pylint>=3.3.7",
    "pytest>=8.3.5",
    "ruff>=0.11.11",
]
types = [
    "types-pyyaml>=6.0.12.20250516",
]
