[project]
name = "ditl-pyarrow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jochen Gietzen", email = "jochen.gietzen@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ditl",
    "pyarrow>=23.0.1",
    "pyarrow-stubs>=20.0.0.20251215",
]

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[tool.uv]
package = true

[tool.uv.sources]
ditl = { workspace = true }
