name: 'ci' 
on:
  pull_request:

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Ensure SSH and gitconfig exist
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.gitconfig

      # - uses: devcontainers/ci@v0.3
      #   with:
      #     imageName: ghcr.io/${{ github.repository }}-devcontainer
      #     runCmd: |
      #       uv run pytest
      #       uv run ruff check .

      - name: Run style & code checks
        uses: devcontainers/ci@v0.3
        with:
          inheritEnv: false
          cacheFrom: ghcr.io/jochengietzen/ditl-devcontainer
          push: never
          runCmd: just check
          env: |
            CI=true
  
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          python: [ "3.13", "3.14" ]
          os: [ ubuntu-latest, macos-latest, windows-latest ]
    defaults:
      run:
          shell: bash
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          path: "./ditl"

      - name: Move repostiory to home
        run: |
            mv $GITHUB_WORKSPACE/ditl /home/runner/work/ditl

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.11.14"
          python-version: ${{ matrix.python }}
          working-directory: $GITHUB_WORKSPACE/ditl

      - name: Install command runner
        uses: taiki-e/install-action@just

      - name: Install Python dependencies
        working-directory: /home/runner/work/ditl
        run: |
            uv sync --all-groups

      - name: Run unit-tests
        working-directory: /home/runner/work/ditl
        run: |
            just unit-tests
