[project]
name = "eltstar-engine-polars"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    {name = "Tim Bossenmaier", email="bossenti@posteo.de"},
    {name = "Jochen Gietzen", email="jochen.gietzen@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "eltstar",
    "polars>=1.34.0",
]

[tool.uv]
package = true

[tool.uv.sources]
eltstar = { workspace = true }

[project.scripts]
eltstar-engine-polars = "eltstar_engine_polars:main"

[project.entry-points."eltstar.wrapper_functions"]
join = "eltstar_engine_polars.functions.join"


[tool.uv.build-backend]
module-name = ["eltstar_engine_polars"]
module-root = "src"

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"
